### ISSUE TITLE
7.20 to-do

### ISSUE THREAD

**Issue by Ashley1014** [Ashley1014/qualtrics#1]
- [ ] Copy over all code from your version to my version and change prices, check to see if IDs need to be changed, and change number of statements
- [ ] Copy/adapt code to new questions - Round 2, Price Reduction
- [ ] Change discount treatment - same final price, double original price (currently, half final price, same original price)
- [ ] Price reduction treatment - same as non-discounted treatments, except double the price (nothing crossed out) --> this mean increment doubles
- [ ] Check over everything in my version
