### ISSUE TITLE
Time Preferences

### ISSUE THREAD

**Issue by aunarang** [Ashley1014/qualtrics#10]
**Time preferences questions:**
Does auto-populating work for both time preferences questions in the block? I only see it for one.

But actually now I want to allow:

1. one switchpoint with switching from A to B
2. all Choice A
3. all Choice B
4. one switchpoint with switching from B to A. This pattern was not allowed before. However, this means we need a different auto-populating mechanism.

Would this implement this?

- First time respondent switches from A to B, then select B for higher decision numbers and A for lower decision numbers. 
- First time respondent switches from B to A then select A for higher decision numbers and B for lower decision numbers.
- If there is a switch, but it not across consecutive decision numbers, that should not matter -- basically some decisions in between will not be selected but with forced response, they will have to select something if they do not.
- If there is no switch, do nothing.

**Tasks**
- [ ] autopopulating mechanism for timepref_1
- [ ] autopopulating mechanism for timepref_2
- [ ] store the equivalent of lower_bound_led, lower_bound_hal, upper_bound_led,, upper_bound_hal for timepref_1
- [ ] store the equivalent of lower_bound_led, lower_bound_hal, upper_bound_led,, upper_bound_hal for timepref_2
- [ ] store choice pattern for timepref_1: whether it was all A, all B, B to A, or A to B as well (4 possible)? Would need to create a new variable.
- [ ] store choice pattern for timepref_2: whether it was all A, all B, B to A, or A to B as well (4 possible)?
