### ISSUE TITLE
Power Strip Lottery (New Task, not Bug)

### ISSUE THREAD

**Issue by aunarang** [Ashley1014/qualtrics#4]
@Ashley1014 

**Description of Power Strip Lottery:**
All respondents will enter a power strip lottery. 1 in 30 respondents will be chosen to receive power strips and possibly a bonus payment. Among those respondents who are chosen, I will choose one of the decisions in the MPLs or FMPLs to implement. Respondents who win the lottery get a budget of $34 (this is the maximum price  of the power strips). They use that budget to pay for the power strip of their choice at the price of their preferred power strip in the decision gets implemented. 

Ex: Let's say decision 7 is chosen. Price of smart power strip in decision 7 is $10. Price of traditional power strip in decision 7 is $5. Respondent chooses traditional power strip. Then they pay $5 for traditional power strip, and they get their budget minus the price of preferred strip as bonus payment, which is $34 - $5 = $29. And then I mail them traditional power strips.

**Task Description:**
I need code that chooses the respondent, the decision that gets implemented, stores the prices of both power strip types in the decision that gets implemented, and stores the power strip type that gets chosen in the decision that gets implemented. 

Each round has 5 main decisions and 5 follow up decisions.

The number of rounds depends on the treatment, and thus the number of decisions will depend on treatment. Those in the No Info and No Info x Discount treatments will go through 2 rounds, 10 main decisions and 10 follow up decisions. Those in the Deliberation Only treatment will go through 1 round, 5 main decisions and 5 follow up decisions. Everybody else goes through three rounds.

All the prices in the main MPL are the same. So for three rounds, for example, there are three sets of repeated prices. The prices of the FMPL may differ across respondent depending on their choices in the main MPL.

e.g for three rounds, there are 30 total decisions (15 main, 15 follow-up). There is one switchpoint per 5 main decisions. If all choice A is selected in main MPL, then switchpoint can be considered to be the first decision in the main MPL. For all choice B, the switchpoint can be considered to be the last decision in the main MPL. 

The implemented decision should be chosen among the 15 main decisions -- i.e. select a random integer from 1 to 15, where this integer denotes the decision number -- UNLESS the decision that gets selected is also a switchpoint.

Specifically,
If main decision number that gets selected !== (is not equal to) decision number of any of the three switchpoints in the main MPL, then keep that decision as the final one to implement.

**The following and the tasks below are my ideas for implementation. If you may have a better way of implementing this, then you can try it.**

e.g. see tasks below: if dec_ mpl_implement !== dec_switch_R1_mpl or dec_switch_R2_mpl or dec_switch_R3_mpl,
then dec_final = dec_mpl_implement

If main decision number that gets selected = decision number of any of the three switchpoints in the main MPL, then select one of the five follow-up decisions from the FMPL associated with that FMPL  to be implemented.

e.g. see tasks below: if dec_ mpl_implement == dec_switch_R1_mpl or dec_switch_R2_mpl or dec_switch_R3_mpl,
then dec_final = dec_fmpl_implement.

**Tasks**

Create the following embedded data variables in survey flow.
- [ ] lottery_implement = ${rand://int/1:30}. There are 1 in 30 lottery winners.
- [ ] dec_final == set in Javascript. See description above.
- [ ] dec_ mpl_implement = ${rand://int/1:15} . 1 of 15 main decisions are selected for first step in deciding which decision to implement.

        if dec_mpl_implement is from 1:5 --> a decision in R1 gets selected. 
        if dec_mpl_implement is from 6:10 --> a decision in R2 gets selected
        if dec_mpl_implement is from 11:15 --> a decision in R3 gets selected

- [ ] dec_fmpl_implement_step1 = ${rand://int/1:5} . 1 of 5 follow up decisions are implemented if switchpoint decision in main MPL is selected. 
- [ ] dec_fmpl_implement =  15 + dec_fmpl_implement_step1. This is so that dec_final ranges from 1 to 30. If dec_final ranges from 16-30, then a FMPL decision gets selected as the final decision to implement.

- [ ] dec_switch_R1_mpl == value set in Javascript based on respondent's selections. This is the decision number of switchpoint in R1_mpl.
- [ ] dec_switch_R2_mpl == value set in Javascript based on respondent's selections. This is the decision number of switchpoint in R2_mpl.
- [ ] dec_switch_R3_mpl == value set in Javascript based on respondent's selections. This is the decision number of switchpoint in R3_mpl.

- [ ] choice_implement == set in Javascript. Should be the type of product chosen, smart or traditional, depending on power strip type chosen in dec_final.
- [ ] price_implement == set in Javascript. Should be price of power strip type chosen in dec_final.
- [ ] price_implement_other == set in Javascript. Should be price of power strip type NOT chosen in dec_final.
- [ ] bonus_payment = $e{ e://Field/budget - e://Field/price_implement }

For the above four embedded data variables, it may be necessary (?) to store the price of Choice A and Choice B in every decision respondents faces -- there will be 30 decisions max x 2 product types = 60 variables. I think we have to store in embedded data variables if they are to be accessed later ,right?

I think is is necessary (?) to store whether Choice A and Choice B gets selected in every decision respondents faces for access later-- this means there would be 30 variables indicating product type chosen (1 per decision). 

- [ ] implement checks that right value is stored for choice_implement, price_implement and bonus_payment because I will be using this to administer the lottery! e.g. can check against stored wtp, other stored values. If wtp is positive and is higher than the price of the smart power strip in the decision that gets selected for implementation, then smart power strip is chosen.
